Feature/skip steps
ebi-gene-expression-group/bulk-recalculations pull request #5
Opened 2021-08-25 12:40 UTC by pmb59

Changes to address rule skipping for specific experiments in bulk recalculations - as specified in a YAML file.

2021-08-25 13:08 UTC, pcm32 requested changes
Thanks for this. Some minor suggestions to improve this.

2021-08-25 13:08 UTC, pcm32 commented on Snakefile
> +        return [" "]
just load data into dictionary, no need for returning it, as it is done with the metadata file

2021-08-25 13:08 UTC, pcm32 commented on Snakefile-sorting-hat
> +            skip_steps_file={params.skip_steps_file} \
this should happen only if provided, so this line shouldn't alway appear.

2021-08-25 13:08 UTC, pcm32 commented on Snakefile
> +    if 'percentile-ranks' in config['tool'] or config['tool']=="all-diff" and config['accession'] not in skip_accesion['skips']['percentile-ranks']:
on this sort of checks you need to protect from the case where skip_accession is empty (you will get an error due to missing key). I would write something like:

```
def skip(accession, tool):
    # if all the keys exist in skip_accession, check for the accession inside the tool part
    # if it has to skip:
    return true
```

and then call that everywhere (will make statements shorter as well).

2021-08-25 13:08 UTC, pcm32 commented on Snakefile-sorting-hat
> +    return config['skip_steps_file']
again, consider the case when this key is not defined. Probably same applies to 'delete_previous_output' above.

2021-08-25 14:04 UTC, pmb59 commented on Snakefile
> +        return [" "]
Returning empty list if yaml is absent was suitable for `not in skip_accesion['skips']`. In any case, I'll remove it

2021-08-25 16:00 UTC, pmb59 commented
NOTE: I've fixed in the last 2 commits a couple of issues related to the GFF.

2021-08-26 09:54 UTC, pcm32 approved these changes
Great work! Thanks for addressing my concerns.

2021-08-26 12:02 UTC, merged